### ISSUE TITLE
It's not working. It just says 'An Error has occurred'.

### ISSUE THREAD

**Issue by ikki4** [notFaad/coom-dl#17]
![image](https://github.com/notFaad/coom-dl/assets/38467650/3582aab7-3f12-4969-8ca4-5166c798e84b)

**Comment by notFaad** [comment]
Can you try with the latest version please, 0.72

**Comment by ikki4** [comment]
Still not working for me, sadly. Same error. But I think the problem is my internet, not your program. When I try to open on Firefox the "Coomer/Kemono Creator Page" link you used in your testings, the link won't open (Error code: SSL_ERROR_RX_RECORD_TOO_LONG). But when I try opening this link on Opera browser with VPN on, it opens correctly. So maybe my ISP/DNS is blocking coomer, or idk. I'll maybe try changing DNS server tomorrow, but anyways, you can close this issue if you want.

![image](https://github.com/notFaad/coom-dl/assets/38467650/0dbebce8-f089-46fa-a913-8d0557ee2e54)

![image](https://github.com/notFaad/coom-dl/assets/38467650/6225f225-3902-40e5-b4c4-5cad737d765d)

**Comment by ikki4** [comment]
I tested it in another PC in my house, and it worked. The problem is my PC, not my internet. I don't know what the problem is, though, but there's no issue with your program. Sorry for the inconvenience. Thank you for developing this great downloader!

**Comment by notFaad** [comment]
I think it may be a problem with your PC's DNS or network settings.
The program begins crawling which means that the link is validated internally.
during the crawl when http request is fetched it is stopped or blocked by your PC's network. This explains why no crawling log is being displayed.

There is nothing wrong with your PC it beings crawling which is a good indicator. The problem is your PC is not allowing 
coom-dl to use your network.
Try the following:
1- Run coom-dl as an admin.
2- Download a VPN (1.1.1.1 WARP or NordVPN)
3- Restore your network settings in the PC (If 1 and 2 didn't work)

**Comment by ikki4** [comment]
It was my freaking antivirus. It decided months ago to start blocking all coomer websites/servers without notifying me, and I only noticed it today.

Again, sorry for the inconvenience, and thanks for trying to help me.
