### ISSUE TITLE
would it be possible to allow it to work in the background? as in in the taskbar tray

### ISSUE THREAD

**Issue by luzenn** [notFaad/coom-dl#2]

**Comment by hecc01** [comment]
also im not sure why the downloader seems to close by itself (not sure if it is because it is done with its task or because it is a crash)

**Comment by notFaad** [comment]
> also im not sure why the downloader seems to close by itself (not sure if it is because it is done with its task or because it is a crash)

in version 0.18 the downloader exits by it self to stop any thread_locks malfunctions, please use version 0.27 as the issue was fixed.

As for the first question the downloader works in background to fetch, download,and crawl data. if that's not what you mean then could you elaborate furthermore.

**Comment by hecc01** [comment]
I am currently already using 0.27, and it is still exiting by itself midway of downloading something. I tried downloading stuff from another creator with significantly less albums and it seems to work fine though. Maybe the creator I am downloading from just has too much stuff lol

**Comment by notFaad** [comment]
> I am currently already using 0.27, and it is still exiting by itself midway of downloading something. I tried downloading stuff from another creator with significantly less albums and it seems to work fine though. Maybe the creator I am downloading from just has too much stuff lol

Oh no sorry about that, can you send me the link to the creator page.

**Comment by luzenn** [comment]
[hong kong doll on coomer](https://coomer.su/onlyfans/user/hongkongdoll)

**Comment by notFaad** [comment]
Ok i see the problem, it's doesn't have to do with the size of the albums, but the size of the video or images your downloading
i'm going to fix this in 0.32 (next version).
The issue is that i'm storing the whole video into RAM before writing it to a file,
so when the video is large it's going to be stored in the ram temporarly before it's written in a file this causes memory overload to your RAM.
Don't worry i'm going to directly hook the http request to a file without touching the ram in the next version.

Again im so sorry for this.

**Comment by notFaad** [comment]
I'm going to rewrite the threadDownloader function from sync to async and make it listen to byte changes, so this way the video you're downloading gets injected directly to a file without storing the whole thing into the ram before injected to a file.

**Comment by notFaad** [comment]
Instead of this [Coomer ->16GB video in memory(RAM)->Write to file from memory]
it's going to be this [Coomer_Streamer->Write each byte from coomer to File -> 16GB file]
i'm not going to wait for the whole thing to finish, just write as you go, but this may lead to file corruption, if http Stream is not stable

**Comment by notFaad** [comment]
Better than nothing i guess lol

Sorry again.

**Comment by notFaad** [comment]
just fixed it will release 0.32 in 3 hours or so

Thank you!

**Comment by notFaad** [comment]
Version 0.32 is released! [Here!](https://github.com/notFaad/coom-dl/releases/tag/0.32)

**Comment by luzenn** [comment]
thanks for the work, much appreciated!
